import React from 'react'

const Lorem = () => {
  return (
    <div>
        <div className="">
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere, quia distinctio fugit debitis explicabo animi ex maxime veritatis sed molestias nostrum, a quisquam ipsam sint fugiat ipsa neque repellendus exercitationem deleniti reiciendis illum praesentium consequatur? Quo minus adipisci harum tempore maxime consequatur temporibus tenetur? Consectetur numquam dolores rem nam dolor exercitationem repellat fuga. Tempora corporis minus sint hic doloribus, dolore quasi ut? Facilis quam ut corrupti culpa temporibus ab et porro dignissimos quisquam laudantium, blanditiis praesentium libero asperiores odit, eaque ea. Earum hic nesciunt aut, dolore corrupti possimus consectetur molestias facere, voluptatibus doloremque voluptas! Modi accusamus tempora molestias dicta hic dolores id, error vero. Quos vero eum aperiam velit temporibus assumenda, accusantium iure maiores autem error? Aliquam eveniet voluptas ducimus. Vel velit consequuntur praesentium? Quos eligendi laudantium nisi, nobis, beatae rem amet aspernatur quod aliquid dolorum iure totam alias reprehenderit cumque numquam dignissimos reiciendis consequatur maxime illo iste, debitis dolore facilis a blanditiis! Obcaecati placeat aut praesentium ducimus laudantium iusto accusamus minus sit, alias ipsam maxime nulla veritatis voluptas, quidem quia quas nesciunt dicta illo itaque temporibus minima expedita hic? Magni officiis et nobis in voluptatibus aperiam ab enim obcaecati vitae error? Exercitationem voluptate sed corrupti necessitatibus. Repudiandae, delectus exercitationem.</p>
        </div>
        <div className="">
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere, quia distinctio fugit debitis explicabo animi ex maxime veritatis sed molestias nostrum, a quisquam ipsam sint fugiat ipsa neque repellendus exercitationem deleniti reiciendis illum praesentium consequatur? Quo minus adipisci harum tempore maxime consequatur temporibus tenetur? Consectetur numquam dolores rem nam dolor exercitationem repellat fuga. Tempora corporis minus sint hic doloribus, dolore quasi ut? Facilis quam ut corrupti culpa temporibus ab et porro dignissimos quisquam laudantium, blanditiis praesentium libero asperiores odit, eaque ea. Earum hic nesciunt aut, dolore corrupti possimus consectetur molestias facere, voluptatibus doloremque voluptas! Modi accusamus tempora molestias dicta hic dolores id, error vero. Quos vero eum aperiam velit temporibus assumenda, accusantium iure maiores autem error? Aliquam eveniet voluptas ducimus. Vel velit consequuntur praesentium? Quos eligendi laudantium nisi, nobis, beatae rem amet aspernatur quod aliquid dolorum iure totam alias reprehenderit cumque numquam dignissimos reiciendis consequatur maxime illo iste, debitis dolore facilis a blanditiis! Obcaecati placeat aut praesentium ducimus laudantium iusto accusamus minus sit, alias ipsam maxime nulla veritatis voluptas, quidem quia quas nesciunt dicta illo itaque temporibus minima expedita hic? Magni officiis et nobis in voluptatibus aperiam ab enim obcaecati vitae error? Exercitationem voluptate sed corrupti necessitatibus. Repudiandae, delectus exercitationem.</p>
        </div>
        <div className="">
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere, quia distinctio fugit debitis explicabo animi ex maxime veritatis sed molestias nostrum, a quisquam ipsam sint fugiat ipsa neque repellendus exercitationem deleniti reiciendis illum praesentium consequatur? Quo minus adipisci harum tempore maxime consequatur temporibus tenetur? Consectetur numquam dolores rem nam dolor exercitationem repellat fuga. Tempora corporis minus sint hic doloribus, dolore quasi ut? Facilis quam ut corrupti culpa temporibus ab et porro dignissimos quisquam laudantium, blanditiis praesentium libero asperiores odit, eaque ea. Earum hic nesciunt aut, dolore corrupti possimus consectetur molestias facere, voluptatibus doloremque voluptas! Modi accusamus tempora molestias dicta hic dolores id, error vero. Quos vero eum aperiam velit temporibus assumenda, accusantium iure maiores autem error? Aliquam eveniet voluptas ducimus. Vel velit consequuntur praesentium? Quos eligendi laudantium nisi, nobis, beatae rem amet aspernatur quod aliquid dolorum iure totam alias reprehenderit cumque numquam dignissimos reiciendis consequatur maxime illo iste, debitis dolore facilis a blanditiis! Obcaecati placeat aut praesentium ducimus laudantium iusto accusamus minus sit, alias ipsam maxime nulla veritatis voluptas, quidem quia quas nesciunt dicta illo itaque temporibus minima expedita hic? Magni officiis et nobis in voluptatibus aperiam ab enim obcaecati vitae error? Exercitationem voluptate sed corrupti necessitatibus. Repudiandae, delectus exercitationem.</p>
        </div>
        <div className="">
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere, quia distinctio fugit debitis explicabo animi ex maxime veritatis sed molestias nostrum, a quisquam ipsam sint fugiat ipsa neque repellendus exercitationem deleniti reiciendis illum praesentium consequatur? Quo minus adipisci harum tempore maxime consequatur temporibus tenetur? Consectetur numquam dolores rem nam dolor exercitationem repellat fuga. Tempora corporis minus sint hic doloribus, dolore quasi ut? Facilis quam ut corrupti culpa temporibus ab et porro dignissimos quisquam laudantium, blanditiis praesentium libero asperiores odit, eaque ea. Earum hic nesciunt aut, dolore corrupti possimus consectetur molestias facere, voluptatibus doloremque voluptas! Modi accusamus tempora molestias dicta hic dolores id, error vero. Quos vero eum aperiam velit temporibus assumenda, accusantium iure maiores autem error? Aliquam eveniet voluptas ducimus. Vel velit consequuntur praesentium? Quos eligendi laudantium nisi, nobis, beatae rem amet aspernatur quod aliquid dolorum iure totam alias reprehenderit cumque numquam dignissimos reiciendis consequatur maxime illo iste, debitis dolore facilis a blanditiis! Obcaecati placeat aut praesentium ducimus laudantium iusto accusamus minus sit, alias ipsam maxime nulla veritatis voluptas, quidem quia quas nesciunt dicta illo itaque temporibus minima expedita hic? Magni officiis et nobis in voluptatibus aperiam ab enim obcaecati vitae error? Exercitationem voluptate sed corrupti necessitatibus. Repudiandae, delectus exercitationem.</p>
        </div>
        <div className="">
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere, quia distinctio fugit debitis explicabo animi ex maxime veritatis sed molestias nostrum, a quisquam ipsam sint fugiat ipsa neque repellendus exercitationem deleniti reiciendis illum praesentium consequatur? Quo minus adipisci harum tempore maxime consequatur temporibus tenetur? Consectetur numquam dolores rem nam dolor exercitationem repellat fuga. Tempora corporis minus sint hic doloribus, dolore quasi ut? Facilis quam ut corrupti culpa temporibus ab et porro dignissimos quisquam laudantium, blanditiis praesentium libero asperiores odit, eaque ea. Earum hic nesciunt aut, dolore corrupti possimus consectetur molestias facere, voluptatibus doloremque voluptas! Modi accusamus tempora molestias dicta hic dolores id, error vero. Quos vero eum aperiam velit temporibus assumenda, accusantium iure maiores autem error? Aliquam eveniet voluptas ducimus. Vel velit consequuntur praesentium? Quos eligendi laudantium nisi, nobis, beatae rem amet aspernatur quod aliquid dolorum iure totam alias reprehenderit cumque numquam dignissimos reiciendis consequatur maxime illo iste, debitis dolore facilis a blanditiis! Obcaecati placeat aut praesentium ducimus laudantium iusto accusamus minus sit, alias ipsam maxime nulla veritatis voluptas, quidem quia quas nesciunt dicta illo itaque temporibus minima expedita hic? Magni officiis et nobis in voluptatibus aperiam ab enim obcaecati vitae error? Exercitationem voluptate sed corrupti necessitatibus. Repudiandae, delectus exercitationem.</p>
        </div>
    </div>
  )
}

export default Lorem